### ISSUE TITLE
LDpair - issue with output="table" when SNPs are in linkage equilibrium

### ISSUE THREAD

**Issue by n-mounier** [timyers/ldlinkr#5]
Hello,

I am really happy to see that this package exists, I have been using LDlink once in a while in the past years, and having some functions to do it easily with R without struggling with the request format and how to parse the output every time is very nice: thank you! :)

I can run your example ` LDpair(var1 = "rs3", var2 = "rs4", pop = "YRI", token = Sys.getenv("LDLINK_TOKEN"))` without any problem, but I have been having some issue when using pairs of SNPs that are not in LD.

```
library(LDlinkR)      
my_var1 <- "rs2860773"       
my_var2 <- "rs2631669"      
```

Using `output = text`, everything works:
```
LDpair(my_var1, 
            my_var2, 
            pop="EUR", 
            token=Sys.getenv("LDLINK_TOKEN"),  output = "text")
# Query SNPs:
# rs2860773 (chr2:65665641)
# rs2631669 (chr2:66104881)
#
# EUR Haplotypes:
#                rs2631669
#                C       T
#              -----------------
#            G | 326   | 273   | 599   (0.595)
# rs2860773    -----------------
#            T | 210   | 197   | 407   (0.405)
#              -----------------
#                536     470     1006
#               (0.533) (0.467)
# 
#           G_C: 326 (0.324)
#           G_T: 273 (0.271)
#           T_C: 210 (0.209)
#           T_T: 197 (0.196)
#
#           D': 0.0316
#           R2: 0.0008
#       Chi-sq: 0.778
#      p-value: 0.3777
#
#  rs2860773 and rs2631669 are in linkage equilibrium
```

But using `output = table` (default), I get this error message:
```
LDpair(my_var1, 
            my_var2, 
            pop="EUR", 
            token=Sys.getenv("LDLINK_TOKEN")
# Error in z[[22]] : subscript out of bounds
```

From what I understand, it comes from your function `table_out()` that expects 22 lines as it is when variants are in LD (in your example):   
`21 : "rs3(C) allele is correlated with rs4(A) allele"`
`22 : "rs3(T) allele is correlated with rs4(G) allele"`
But when variants are actually in linkage equilibrium, these two lines are replaced by a single one (my example):    
`21 : "rs2860773 and rs2631669 are in linkage equilibrium"`

This should be quite easy to fix! ;)
Thanks again for this very useful package!

**Comment by timyers** [comment]
Issued fixed in the dev version available on github.  It will be included in the next upload to CRAN.
Thanks for reporting it.

**Comment by timyers** [comment]
Fix included in v.1.0.2.
